@baseUrl = http://localhost:3333


###
POST http://localhost:3333/users
content-type: application/json

{
    "name": "Joao",
    "email": "joaog2@acme.com",
    "password": "1233"
}

###
POST {{baseUrl}}/sessions/password
content-type: application/json

{
    "email": "joaog@acme.com",
    "password": "123123"
}

###
GET {{baseUrl}}/profile
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM1ZWM5NS03NDQ1LTRlZGYtOTk2MS1mNWIxZjlmODQ2Y2UiLCJpYXQiOjE3NTk4Mjc2ODksImV4cCI6MTc2MDQzMjQ4OX0.mGxGhDR29lQSz5EVunsGnRkEFNB02YfeeGcWxuERFCE