services:
  pg:
    image: bitnami/postgresql:latest
    container_name: next-saas-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=next-saas
